### ISSUE TITLE
Plugin Struktur anpassen

### ISSUE THREAD

**Issue by plakos** [plakos/plakos-moodle-rest-api#3]
Hi Artur,

könntest du die Anpassungen des Plugins ab jetzt übernehmen. Hier ist das Feedback von Lern.Link dazu:
von [lern.link GmbH](https://lernen.plakos-akademie.de/user/view.php?id=2&course=3) - Dienstag, 2. April 2024, 13:45
Hallo Waldemar,

danke für die Einladungen zu Eurem Github Repo. Ich übernehme hier nun von Nicole.

Nicole hatte Euch oben ja auch schon meine initialen Kommentare zum Plugin übergeben, ich sehe auch dass das Plugin in Teilen schon angepasst wurde. Danke dafür.

Leider passt aber die Repo-Struktur noch nicht. Die Konvention für Moodle Plugin Repos in Github ist dass das Plugin auf der obersten Ebene - und nicht in einem Unterordner - geliefert wird. Ebenso ist es wünschenswert dass nur das Plugin und keine weiteren Dateien für IDE-Konfigurationen, Docker-Configs und eigentlich auch keine Composer Files (solange sie nicht für den Build-Prozess des Plugins essentiell sind, Moodle selbst nutzt aktuell kein Composer) enthalten sind.

Ich sehe auch noch nicht dass Moodle-Plugin-CI integriert ist, auf https://github.com/plakos/plakos-moodle-rest-api/actions sind nur drei fehlgeschlagene Workflows zu sehen.

Kannst Du Euren Entwickler bitten das noch zu bereinigen? Danach kann ich das Plugin initial ausrollen.

Vielen Dank & viele Grüße
Alexander Bias
- Development & Operations Manager -
![image](https://github.com/plakos/plakos-moodle-rest-api/assets/14232779/7bbb311d-f697-4a7a-90de-b7082a243ab8)

**Comment by uberneu** [comment]
Hallo Waldemar, Hallo Artur,

ich hatte schon vor diesem Task ein paar Anpassungen vorgenommen und jetzt einfach gepushed, damit sie nicht verloren gehen. Ich hoffe Du (Artur) hast bisher nichts daran gemacht. 

Ab jetzt kann Artur übernehmen und ich halte mich bis auf Weiteres aus diesem Projekt raus.

Die moodle-plugin-ci Tests laufen durch, es gibt aber keine PHPUnit/Behat Tests.

LG, Ben
